dataset: "LRS"

path:
  corpus_path: "/ssd_scratch/cvit/souvik/mvlrs_v1/pretrain/"
  lexicon_path: "/ssd_scratch/cvit/souvik/L2T-TTS-ALL_CODES/ssd_scratch/cvit/sindhu/MFA/pretrained_models/dictionary/english_us_arpa.dict"
  raw_path: "/ssd_scratch/cvit/souvik/mvlrs_v1/pretrain/"
  preprocessed_path: "/ssd_scratch/cvit/souvik/mvlrs_v1/pretrain/"

preprocessing:
  img_size: 160
  upsample_scale: 3.44
  upsample_scale_mel: 4
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 16000
    max_wav_value: 32768
  stft:
    # filter_length: 743
    # hop_length: 186
    # win_length: 743
    filter_length: 512
    hop_length: 160
    win_length: 400
  # audio:
  #   sampling_rate: 22050
  #   max_wav_value: 32768.0
  # stft:
  #   filter_length: 1024
  #   hop_length: 256
  #   win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
